@TodoApi_HostAddress = https://azure-copilot-demo.azurewebsites.net/

### TodoApi

POST {{TodoApi_HostAddress}}/api/TodoItems
Content-Type: application/json

  {
    "Name": "Write a blog",
    "IsComplete": true
  }

###
GET {{TodoApi_HostAddress}}/api/TodoItems
Accept: application/json

### Get one
GET {{TodoApi_HostAddress}}/api/TodoItems/1

### Update
PUT {{TodoApi_HostAddress}}/api/TodoItems/3
Content-Type: application/json

  {
    "Id": 3,
    "Name": "Study for End Year Exams",
    "IsComplete": false
  }

### Delete
DELETE {{TodoApi_HostAddress}}/api/TodoItems/3

 
