@TodoApi_HostAddress = http://localhost:5161

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### TodoApi

POST {{TodoApi_HostAddress}}/api/TodoItems
Content-Type: application/json
  {
    "Name": "Study for Exams",
    "IsComplete": false
  }

  ###
GET {{TodoApi_HostAddress}}/api/TodoItems
Accept: application/json

### Get one
GET {{TodoApi_HostAddress}}/api/TodoItems/1

### Update
PUT {{TodoApi_HostAddress}}/api/TodoItems/3
Content-Type: application/json
  {
    "Id": 3,
    "Name": "Study for End Year Exams",
    "IsComplete": false
  }

  ### Delete
  DELETE {{TodoApi_HostAddress}}/api/TodoItems/3
